version: "{{ config.docker_compose_version }}"

services:
{% for service, data in settings %}
    {{ service }}:
        environment:
            VIRTUAL_HOST: {{ data.host }}
            VIRTUAP_PORT: {{ data.port }}
        networks:
            - reverse-proxy
{% endfor %}

networks:
    reverse-proxy:
        external:
            name: {{ network_name }}
