version: '2'

services:
    cli:
        build:
          context: .
        environment:
            - HOME=/home/user
            - ORIGINAL_PWD=$PWD
        volumes:
            - "./..:/usr/src/script"
            - "~/:/home/user:ro"
            - "$PWD:$PWD"
        working_dir: $PWD
        entrypoint: /usr/src/script/symfony/bin/docker-entrypoint.sh
