version: '2'

services:
    cli:
        build:
          context: .
        environment:
            - HOME=/home/user
        volumes:
            - "./..:/usr/src/script"
            - "~/:/home/user:ro"
            - "$PWD:/usr/src/myapp"
        working_dir: /usr/src/myapp
        entrypoint: /usr/src/script/symfony/bin/docker-entrypoint.sh
