stages:
    - build
    - test
#    - cleanup

cache:
    key: ${CI_PIPELINE_ID}
    untracked: true
    paths:
        - packages/wf-docker-workflow/opt/wf-docker-workflow/symfony4/vendor
        - packages/wf-docker-workflow/opt/wf-docker-workflow/symfony4/var

variables:
#    WF_DEBUG: 2
    TEST_IMAGE: gitlab-runner/test-wf:${CI_PIPELINE_ID}

.all_jobs: &all_jobs
    tags:
        - wf

build:
    stage: build
    <<: *all_jobs
    script:
#        - docker build --no-cache -t ${TEST_IMAGE} .
        - cp .wf.gitlab-ci.yml .wf.yml
#        - 'sed -e "s|image: fchris82/wf|image: ${TEST_IMAGE}|" -i .wf.yml'
        - cat .wf.yml
        - wf reconfigure
        - wf debug-docker-config
        - wf sfcmd composer install
        - echo "Build 'install-wf.sh' to downlaod."
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - install-wf.sh

test:sh:
    stage: test
    <<: *all_jobs
    script:
        - ./test/functions.sh
    # Change cache policy to make faster the CI pipeline
    cache:
        key: ${CI_PIPELINE_ID}
        untracked: true
        policy: pull

test:phpunit:
    stage: test
    <<: *all_jobs
    script:
        - wf sfcmd vendor/bin/phpunit
    # Change cache policy to make faster the CI pipeline
    cache:
        key: ${CI_PIPELINE_ID}
        untracked: true
        policy: pull

test:phpcsfix:
    stage: test
    <<: *all_jobs
    script:
        - wf sfcmd vendor/bin/php-cs-fixer fix --dry-run
    # Change cache policy to make faster the CI pipeline
    cache:
        key: ${CI_PIPELINE_ID}
        untracked: true
        policy: pull

#cleanup:
#    stage: cleanup
#    <<: *all_jobs
#    script:
#        # @todo Nem tudjuk törölni az aktuálisat, mert éppen használjuk. Vagy legalábbis vmi ilyen hibaüzenetet dob:
#        #   $ docker rmi ${TEST_IMAGE}
#        #   Error response from daemon: conflict: unable to remove repository reference "gitlab-runner/test-wf:5877" (must force) - container 283cbc94d3d9 is using its referenced image 9147dac2a6ff
##        - docker rmi -f ${TEST_IMAGE}
#    when: always
