stages:
    - build
    - test
    - cleanup

cache:
    key: ${CI_PIPELINE_ID}
    untracked: true
    paths:
        - webtown-workflow-package/opt/webtown-workflow/symfony4/vendor
        - webtown-workflow-package/opt/webtown-workflow/symfony4/var

variables:
#    WF_DEBUG: 3
    TEST_IMAGE: gitlab-runner/test-wf:${CI_PIPELINE_ID}

.all_jobs: &all_jobs
    tags:
        - project3
    before_script:
        - ls -al
        - ls -al webtown-workflow-package/opt/webtown-workflow/symfony4

build:
    stage: build
    <<: *all_jobs
    script:
        - docker build --no-cache -t ${TEST_IMAGE} .
        - cp .wf.gitlab-ci.yml .wf.yml
        - 'sed -e "s|image: fchris82/wf|image: ${TEST_IMAGE}|" -i .wf.yml'
        - cat .wf.yml
        - ls -al
        - ls -al webtown-workflow-package
        - ls -al webtown-workflow-package/opt/webtown-workflow
        - ls -al webtown-workflow-package/opt/webtown-workflow/host/bin
        - wf reconfigure
        - wf debug-docker-config
        - wf composer install -d webtown-workflow-package/opt/webtown-workflow/symfony4
        - echo "Build 'install-wf.sh' to downlaod."
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - install-wf.sh

test:deb:
    stage: test
    <<: *all_jobs
    script:
        - rm -rf tmp/deb
        - rm -rf tmp/original
        - wf run engine dpkg-deb -R webtown-workflow.deb tmp/deb
        - git -C webtown-workflow-package ls-files --exclude-standard -oi --directory > .git/ignores.tmp
        - rsync -r --delete --delete-excluded --delete-before --force --exclude=.git --exclude-from="$(echo .git/ignores.tmp)" webtown-workflow-package/* tmp/original
        - DIFF=$(diff -qr tmp/original tmp/deb)
        - rm -rf tmp/deb
        - rm -rf tmp/original
        - if [[ ! -z ${DIFF} ]]; then echo $DIFF; echo "You didn't refresh the deb package! Run the 'make rebuild_wf' command and commit the new deb package too!"; exit 1; fi
    # Change cache policy to make faster the CI pipeline
    cache:
        key: ${CI_PIPELINE_ID}
        untracked: true
        policy: pull

test:sh:
    stage: test
    <<: *all_jobs
    script:
        - ./test/functions.sh
    # Change cache policy to make faster the CI pipeline
    cache:
        key: ${CI_PIPELINE_ID}
        untracked: true
        policy: pull

test:phpunit:
    stage: test
    <<: *all_jobs
    script:
        - cd webtown-workflow-package/opt/webtown-workflow/symfony4 wf run bin/phpunit
    # Change cache policy to make faster the CI pipeline
    cache:
        key: ${CI_PIPELINE_ID}
        untracked: true
        policy: pull

test:phpcsfix:
    stage: test
    <<: *all_jobs
    script:
        - ./webtown-workflow-package/opt/webtown-workflow/host/bin/workflow_runner.sh --develop wf --dev --sf-run vendor/bin/php-cs-fixer fix --dry-run
    # Change cache policy to make faster the CI pipeline
    cache:
        key: ${CI_PIPELINE_ID}
        untracked: true
        policy: pull

cleanup:
    stage: cleanup
    <<: *all_jobs
    script:
        # @todo Nem tudjuk törölni az aktuálisat, mert éppen használjuk. Vagy legalábbis vmi ilyen hibaüzenetet dob:
        #   $ docker rmi ${TEST_IMAGE}
        #   Error response from daemon: conflict: unable to remove repository reference "gitlab-runner/test-wf:5877" (must force) - container 283cbc94d3d9 is using its referenced image 9147dac2a6ff
        #- docker rmi ${TEST_IMAGE}
        - echo "todo"
    when: always
