stages:
    - build
    - test
    - cleanup

cache:
    key: ${CI_PIPELINE_ID}
    untracked: true

variables:
    SF_RUN: ./webtown-workflow-package/opt/webtown-workflow/host/bin/workflow_runner.sh --develop wf --dev --sf-run
    WF_IMAGE: gitlab-runner/test-wf:${CI_PIPELINE_ID}

.all_jobs: &all_jobs
    tags:
        - project3
    # Change cache policy to make faster the CI pipeline
    cache:
        key: ${CI_PIPELINE_ID}
        untracked: true
        policy: pull

build:
    stage: build
    <<: *all_jobs
    script:
        - docker build --no-cache -t ${WF_IMAGE} .
        - ${SF_RUN} env
        - ${SF_RUN} composer install
        - echo "Build 'install-wf.sh' to downlaod."
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - install-wf.sh

test:deb:
    stage: test
    <<: *all_jobs
    script:
        - rm -rf /tmp/deb
        - rm -rf /tmp/original
        - dpkg-deb -R webtown-workflow.deb /tmp/deb
        - git -C webtown-workflow-package ls-files --exclude-standard -oi --directory > .git/ignores.tmp
        - rsync -r --delete --delete-excluded --delete-before --force --exclude=.git --exclude-from="$(echo .git/ignores.tmp)" webtown-workflow-package/* /tmp/original
        - DIFF=$(diff -qr /tmp/original /tmp/deb)
        - rm -rf /tmp/deb
        - rm -rf /tmp/original
        - if [[ ! -z ${DIFF} ]]; then echo $DIFF; echo "You didn't refresh the deb package! Run the 'make rebuild_wf' command and commit the new deb package too!"; exit 1; fi

test:sh:
    stage: test
    <<: *all_jobs
    script:
        - ./test/functions.sh

test:phpunit:
    stage: test
    <<: *all_jobs
    script:
        - ${SF_RUN} bin/phpunit

test:phpcsfix:
    stage: test
    <<: *all_jobs
    script:
        - ${SF_RUN} vendor/bin/php-cs-fixer fix --dry-run

cleanup:
    stage: cleanup
    <<: *all_jobs
    script:
        - docker rmi ${WF_IMAGE}
    when: always
