stages:
    - build
    - test

.all_jobs: &all_jobs
    tags:
        - project3

build:
    stage: build
    <<: *all_jobs
    script:
        - echo "Only build 'install-wf.sh' to downlaod."
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - install-wf.sh

test:deb:
    stage: test
    <<: *all_jobs
    script:
        - rm -rf /tmp/deb
        - rm -rf /tmp/original
        - dpkg-deb -R webtown-workflow.deb /tmp/deb
        - git -C webtown-workflow-package ls-files --exclude-standard -oi --directory > .git/ignores.tmp
        - rsync -r --delete --delete-excluded --delete-before --force --exclude=.git --exclude-from="$(echo .git/ignores.tmp)" webtown-workflow-package/* /tmp/original
        - DIFF=$(diff -qr /tmp/original /tmp/deb)
        - rm -rf /tmp/deb
        - rm -rf /tmp/original
        - if [[ ! -z ${DIFF} ]]; then echo $DIFF; echo "You didn't refresh the deb package! Run the 'make rebuild_wf' command and commit the new deb package too!"; exit 1; fi

test:tests:
    stage: test
    <<: *all_jobs
    script:
        - make -f test/tests.mk gitlab
