version: "2.0.0"
name: gitlab_wf

docker_compose:
    # Docker Compose yaml configuration. You mustn't use the version parameter, it will be automatically.
    extension:
        services:
            engine:
                image: fchris82/wf
                environment:
                    SYMFONY_DEPRECATIONS_HELPER: disabled
                    CI_COMMIT_REF_NAME: ${CI_COMMIT_REF_NAME}
                    APP_ENV: test

commands:
    cmd:
        - ${@}

    sfcmd:
        - cd packages/wf-docker-workflow/opt/wf-docker-workflow/symfony4
        - ${@}
