#!/bin/bash
# ----------------------------------------------------------------------------------------------------------------------
#                                          C L E A N   O L D   W I Z A R D
# ----------------------------------------------------------------------------------------------------------------------

if dpkg -i | grep webtown-workflow; then
    dpkg -r webtown-workflow
fi

if [ -d /opt/webtown-workflow/lib ]; then
    rm -rf /opt/webtown-workflow
fi

rm -rf /etc/webtown-workflow

SHELL_SCRIPT_RCS=(/etc/bash.bashrc /etc/zsh/zshrc)
for RC_FILE in ${SHELL_SCRIPT_RCS[@]}; do
    if [ -f $RC_FILE ]; then
        CMD="/opt/webtown-workflow/wizard.sh --check-update"
        sed -i "/# Webtown Project Wizard update check/d" $RC_FILE
        sed -i "\|${CMD}|d" $RC_FILE
    fi
done
