FROM fchris82/wf

# Useful paths in ENV
#   - SYMFONY_PATH
#   - SYMFONY_CONSOLE

# Add VCS and the new extension
#RUN cd ${SYMFONY_PATH} && \
#    composer config repositories.repo-name vcs https://github.com/custom/wf-extension.git && \
#    composer require "custom/wf-extension"
