version: "2"

services:
    engine:
        build:
            context: ${PROJECT_COMPOSE_DIR}/engine
            args:
                - PHP_VERSION
                - TIMEZONE
        environment:
            - PHP_VERSION
            - WWW_DATA_UID
            - WWW_DATA_GID
            - TIMEZONE
            - PHP_MAX_EXECUTION_TIME
            - PHP_MEMORY_LIMIT
            - PHP_MAX_UPLOAD
            - PHP_MAX_FILE_UPLOADS
            - PHP_MAX_POST
            - PHP_IDE_CONFIG="serverName=${XDEBUG_IDE_SERVER_NAME}"
            - XDEBUG_ENABLED=${XDEBUG_ENABLED}
        volumes:
            # Full project files
            - "${BASE_DIRECTORY}:${DOCKER_DOC_ROOT}"
            # Entrypoint file
            - "${PROJECT_COMPOSE_DIR}/engine/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro"
            # User SSH keys
            - "${SSH_PATH}:/home/user/.ssh:ro"
            # Git config fájl bekötése
            - "~/.gitconfig:/home/user/.gitconfig:ro"
            # Composer cache
            - "~/.composer:/home/user/.composer"
            # Local settings
            - "${PROJECT_COMPOSE_DIR}/engine/config/custom.php.ini:/etc/php/${PHP_VERSION}/cli/conf.d/99-custom.ini"
            # The FPM can't use the environment variables for config, so we will replace them in `entrypoint.sh` with `envsubst` command
            - "${PROJECT_COMPOSE_DIR}/engine/config/custom.php.ini:/etc/php/${PHP_VERSION}/fpm/conf.d/99-custom.ini.dist"
            - "${PROJECT_COMPOSE_DIR}/engine/config/xdebug.ini:/etc/php/${PHP_VERSION}/cli/conf.d/xdebug.ini"
            - "${PROJECT_COMPOSE_DIR}/engine/config/xdebug.ini:/etc/php/${PHP_VERSION}/fpm/conf.d/xdebug.ini"
#            # Global settings
#            - "~/.docker/custom.php.ini:/etc/php/${PHP_VERSION}/cli/conf.d/99-custom.ini"
#            # The FPM can't use the environment variables for config, so we will replace them in `entrypoint.sh` with `envsubst` command
#            - "~/.docker/custom.php.ini:/etc/php/${PHP_VERSION}/fpm/conf.d/99-custom.ini.dist"
#            - "~/.docker/xdebug.ini:/etc/php/${PHP_VERSION}/cli/conf.d/xdebug.ini"
#            - "~/.docker/xdebug.ini:/etc/php/${PHP_VERSION}/fpm/conf.d/xdebug.ini"
        tty: true
