version: '2'

services:
    cli:
        image: fchris82/wf
        build:
            context: ../.
        environment:
            - HOME=/home/user
            - ORIGINAL_PWD=$PWD
            - APP_ENV=$APP_ENV
            - XDEBUG_ENABLED=$XDEBUG_ENABLED
            - LOCAL_USER_ID=$LOCAL_USER_ID
            - USER_GROUP=$USER_GROUP
        volumes:
            - "/etc/webtown-workflow/config:/etc/webtown-workflow/config"
            - "~/:/home/user:ro"
        working_dir: /home/user
