version: "2.0.0"
name:    "{{ project_name }}"

# The configs of recipes
recipes:
    # Symfony 3 recipe
    symfony3:
        version: php{{ php_version }}
        # Symfony environment.
        env: dev
        server:
            # You can switch on and off the xdebug.
            xdebug:         false
