version: '2'

services:
    cli:
        build:
          context: .
        environment:
            - HOME=/home/user
            - ORIGINAL_PWD=$PWD
        volumes:
            - "./..:/opt/webtown-workflow"
            - "~/:/home/user:ro"
            # We want to allow the configs from Symfony
            - "./../../../etc/webtown-workflow:/etc/webtown-workflow:ro"
        working_dir: /home/user
        entrypoint: /opt/webtown-workflow/symfony4/bin/docker-entrypoint.sh
