# GitLab esetén CSAK ezt a fájlt használjuk! Nem tölti be az eredeti `docker-compose.yml`-t és a `docker-compose.local.yml`-t sem.
version: "2"

services:
    mysql:
        image: mysql:5.6
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        volumes:
            - "${DOCKER_DATA_DIR}/mysql:/var/lib/mysql"

    engine:
        build:
            context: ${PROJECT_COMPOSE_DIR}/engine
            args:
                - PHP_VERSION
                - TIMEZONE
        environment:
            - CI
            - PHP_VERSION
            - WWW_DATA_UID
            - WWW_DATA_GID
            - DATABASE_URL
            - TIMEZONE
            - PHP_MAX_EXECUTION_TIME
            - PHP_MEMORY_LIMIT
            - PHP_MAX_UPLOAD
            - PHP_MAX_FILE_UPLOADS
            - PHP_MAX_POST
            - SYMFONY_ENV
            - SYMFONY_DEBUG
            - SYMFONY_CLASSLOADER_FILE
            - SYMFONY_HTTP_CACHE
            - SYMFONY_HTTP_CACHE_CLASS
            - SYMFONY_TRUSTED_PROXIES
        volumes:
            # Full project files
            - "${BASE_DIRECTORY}:${DOCKER_DOC_ROOT}"
            # Entrypoint file
            - "${PROJECT_COMPOSE_DIR}/engine/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro"
            # User SSH keys
            - "${SSH_PATH}:/home/user/.ssh:ro"
            # Git config fájl bekötése
            - "~/.gitconfig:/home/user/.gitconfig:ro"
            # Composer cache
            - "~/.composer:/home/user/.composer"
