SUDO              :=
DOCKER_PSEUDO_TTY := -T
# @todo (Chris) Itt mint ha nem találná a $COMPOSE_PROJECT_NAME értékét.
DOCKER_BASENAME   := $${COMPOSE_PROJECT_NAME:-$${LOCAL_USER_NAME:-gitlabci}p$${PWD\#\#*/}}
