version: "{{ config.docker_compose.version }}"

services:
    web:
        image: nginx:latest
        links:
            - engine:php
        volumes:
            - "${BASE_DIRECTORY}/${PROJECT_DIR_NAME}:${DOCKER_DOC_ROOT}/${PROJECT_DIR_NAME}"
            - "{{ recipe_path }}/etc/vhost.conf:/etc/nginx/conf.d/default.conf:ro"
        command: {{ nginx_debug ? 'nginx-debug' : 'nginx' }} -g 'daemon off;'

    engine:
        image:  fchris82/symfony:{{ version }}
        environment:
            CI: ${CI}
            DOCKER_RUN: ${DOCKER_RUN}
            COMPOSER_MEMORY_LIMIT: -1
            DOCKER_USER: ${DOCKER_USER}
            DEBUG: ${DEBUG}
            LOCAL_USER_ID: ${LOCAL_USER_ID}
            LOCAL_USER_NAME: ${LOCAL_USER_NAME}
            LOCAL_USER_HOME: ${LOCAL_USER_HOME}
            COMPOSER_HOME: ${LOCAL_USER_HOME}
            LOCALE: {{ server.locale }}
            WWW_DATA_UID: ${WWW_DATA_UID}
            WWW_DATA_GID: ${WWW_DATA_GID}
            DATABASE_URL: ${DATABASE_URL}
            TIMEZONE:                     {{ server.timezone }}
            PHP_MAX_EXECUTION_TIME:       {{ server.timeout }}
            PHP_MEMORY_LIMIT:             128M
            PHP_UPLOAD_MAX_FILESIZE:      {{ server.max_post_size }}
            PHP_MAX_FILE_UPLOADS:         10
            PHP_POST_MAX_SIZE:            {{ server.max_post_size }}
            SYMFONY_ENV:                  {{ env }}
            SYMFONY_DEBUG:                ~
            SYMFONY_CLASSLOADER_FILE:     ~
            SYMFONY_HTTP_CACHE:           ~
            SYMFONY_HTTP_CACHE_CLASS:     ~
            SYMFONY_TRUSTED_PROXIES:      ~
            SYMFONY_DEPRECATIONS_HELPER:  ~
            PHP_IDE_CONFIG: "serverName={{ environment.XDEBUG_IDE_SERVER_NAME | default(server.xdebug_ide_server_name) }}"
            WF_XDEBUG_ENABLED: {{ server.xdebug ? '1' : '0' }}
            XDEBUG_ENABLED: {{ server.xdebug ? '1' : '0' }}
            ERROR_LOG_ENABLED: {{ server.error_log ? '1' : '0' }}
        volumes:
            # Full project files
            - "${BASE_DIRECTORY}:${DOCKER_DOC_ROOT}"
        # It is important to avoid "Exit 0"
        tty: true
