#!/bin/bash
# ----------------------------------------------------------------------------------------------------------------------
#                                                   W I Z A R D
# ----------------------------------------------------------------------------------------------------------------------

########################################################################################################################
#                                                                                                                      #
#   @Permission problem                                                                                                #
#                                                                                                                      #
#   The composer run by root here! The cache and everything will be `root:root` The copied files have correct          #
#   owners.                                                                                                            #
#                                                                                                                      #
#   The solution: we set the owner by a reference file!                                                                #
#                                                                                                                      #
########################################################################################################################


# Set permissions
REFERENCE="/opt/webtown-workflow/wizard.sh"

# @todo (Chris) Ezt kívülről kellene megkapni.
USER=$(ls -ld ${REFERENCE} | cut -d\  -f3)
GROUP=$(stat -c '%g' /var/run/docker.sock)

# Install
APP_ENV=prod WF_SYMFONY_ENV=prod /opt/webtown-workflow/workflow.sh --composer-install --no-dev

# Set the permission if needed
if [ -d /opt/webtown-workflow/symfony4/var ]; then
    chown -R $(id -u ${USER}):$(getent group docker | cut -d: -f3) /opt/webtown-workflow/symfony4/var
    chmod -R 777 /opt/webtown-workflow/symfony4/var/cache
    chmod -R 777 /opt/webtown-workflow/symfony4/var/log
fi

# Create symlinks
ln -sf /opt/webtown-workflow/workflow.sh /usr/local/bin/wf
ln -sf /opt/webtown-workflow/wizard.sh /usr/local/bin/wizard
ln -sf /opt/webtown-workflow/lib/wf-composer-require.sh /usr/local/bin/wf-composer-require
