#!/bin/bash
# REMOVE old symfony
if [ -d /opt/webtown-workflow/symfony ]; then
    rm -rf /opt/webtown-workflow/symfony
fi

# REMOVE old config
if [ -f /etc/webtown-workflow/config ]; then
    rm -rf /etc/webtown-workflow/config
fi

# ----------------------------------------------------------------------------------------------------------------------
#                                          C L E A N   O L D   W I Z A R D
# ----------------------------------------------------------------------------------------------------------------------

# Before union directory
if [ -d /opt/webtown-project-wizard ]; then
    rm -rf /opt/webtown-project-wizard
fi

# Before union packages
if dpkg -i | grep webtown-project-wizard; then
    dpkg -r webtown-project-wizard
fi

if [ -d /opt/webtown-project-wizard/lib ]; then
    rm -rf /opt/webtown-project-wizard
fi

rm -rf /etc/webtown-project-wizard

SHELL_SCRIPT_RCS=(/etc/bash.bashrc /etc/zsh/zshrc)
for RC_FILE in ${SHELL_SCRIPT_RCS[@]}; do
    if [ -f $RC_FILE ]; then
        CMD="/opt/webtown-project-wizard/wizard.sh --check-update"
        sed -i "/# Webtown Project Wizard update check/d" $RC_FILE
        sed -i "\|${CMD}|d" $RC_FILE
    fi
done
